catalog/urls.py
from django.urls import path
from . import views

#TODO urls borrow-books
urlpatterns = [
    path('', views.index, name='index'),
    path('books/', views.BookListView.as_view(), name='books'),
    path('book/<int:pk>', views.BookDetailView.as_view(), name='book-detail'),
    path('author/<int:pk>', views.AuthorDetailView.as_view(), name='author-detail'),
    path('authors/', views.AuthorListView.as_view(), name='authors'),
    path('my-books/', views.LoanedBooksByUserListView.as_view(), name='my-borrowed'),
    path('all-borrowed-nooks/', views.AllLoanedBooksByUsersListView.as_view(), name='all-borrowed-books'),

    path('book-order/delete/<uuid:pk>', views.BookOrderDelete.as_view(), name='book-order-delete'),
    path('book-order/renew/<uuid:pk>', views.renew_book_librarian, name='renew-book-librarian'),
    path('book-order/return/<uuid:pk>', views.BookOrderStatusUpdate.as_view(), name='book-return'),
    path('book-order-returns/', views.AllBooksToReturnListView.as_view(), name='borrowed-books-return'),

    path('authors-edit/', views.AllAuthorsEditListView.as_view(), name='authors-edit'),
    path('author/create/', views.AuthorCreate.as_view(), name='author-create'),
    path('author/<int:pk>/update/', views.AuthorUpdate.as_view(), name='author-update'),
    path('author/<int:pk>/delete/', views.AuthorDelete.as_view(), name='author-delete'),
    path('books-edit/', views.AllBooksEditListView.as_view(), name='books-edit'),
    path('book/create/', views.BookCreate.as_view(), name='book-create'),
    path('book/<int:pk>/update/', views.BookUpdate.as_view(), name='book-update'),
    path('book/<int:pk>/delete/', views.BookDelete.as_view(), name='book-delete'),
]

library/urls.py
from django.conf import settings
from django.conf.urls import url
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView

# TODO URL vs PATH ???!!!
urlpatterns = [
                  url(r'^admin/', admin.site.urls),
                  path('catalog/', include('catalog.urls')),
                  path('accounts/', include('django.contrib.auth.urls')),
                  path('accounts/', include('django_registration.backends.activation.urls')),
                  path('', RedirectView.as_view(url='catalog/', permanent=True))
              ] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

catalog/models.py
import uuid
from datetime import date

from django.contrib.auth.models import User
from django.db import models

from enum import Enum

# class Categories(Enum):
#     Fantasy = 'Fantasy'
#     Horror = 'Horror'
#     History = 'History'
#     Mystery = 'Mystery'
#     Poetry = 'Poetry'
from django.urls import reverse


class Category(models.Model):
    """Category Model"""
    name = models.CharField(max_length=200, help_text="Insert book category")

    def __str__(self):
        """Function to print categories"""
        return self.name


class Language(models.Model):
    """Language Model"""
    name = models.CharField(max_length=200, help_text="Insert book language")

    def __str__(self):
        """Function to print languages"""
        return self.name


class Book(models.Model):
    """Book Model"""
    title = models.CharField(max_length=20, help_text='Book Title')
    category = models.ManyToManyField(Category, help_text='Book Categories', null=True, verbose_name='Category')
    language = models.ForeignKey(Language, on_delete=models.SET_NULL, help_text='Book Language', null=True, verbose_name='Language')
    author = models.ForeignKey('Author', on_delete=models.SET_NULL, null=True, help_text='Book Author')
    # copies = models.CharField(max_length=20, help_text='Book Copies')
    isbn = models.CharField(max_length=13, help_text='Book ISBN')
    description = models.TextField(max_length=1000, help_text='Book Description', verbose_name='Book Description')

    def __str__(self):
        """Function to print title"""
        return self.title

    def get_absolute_url(self):
        """Function return absolute url"""
        return reverse('book-detail', args=[str(self.id)])

    def display_category(self):
        """Function to display all categories"""
        return ', '.join(category.name for category in self.category.all())


class Author(models.Model):
    """Author Model"""
    name = models.CharField(max_length=20, help_text='Author Name')
    surname = models.CharField(max_length=20, help_text='Author Surname')
    date_of_birth = models.DateField(null=True, blank=True, verbose_name='Date Birth')
    date_of_death = models.DateField(null=True, blank=True, verbose_name='Date Death')

    def get_absolute_url(self):
        """Function return absolute url"""
        return reverse('author-detail', args=[str(self.id)])

    def __str__(self):
        """Function to print author"""
        return f'{self.name} {self.surname}'


class BookOrder(models.Model):
    """BookOrder Model"""
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, help_text='Unique ID')
    book = models.ForeignKey(Book, on_delete=models.SET_NULL, null=True, verbose_name='Book title')
    #TODO user (?)
    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True, max_length=20, help_text='User')
    date_of_return = models.DateField(null=True, blank=True, verbose_name='Date Return')
    imprint = models.CharField(max_length=200)

    STATUS = (
        ('m', 'maintenance'),
        ('o', 'on loan'),
        ('a', 'available'),
        ('r', 'reserved')
    )

    status = models.CharField(
        max_length=1,
        choices=STATUS,
        blank=True,
        default='m',
        help_text="Book Status"
    )

    class Meta:
        """Meta class ordering by date return book"""
        ordering = ['date_of_return']
        permissions = (("can_mark_returned", "Set book as returned"),)

    def __str__(self):
        """Function to display Book Order"""
        return f'{self.id} ({self.book.title})'

    @property
    def is_overdue(self):
        if self.date_of_return and date.today() > self.date_of_return:
            return True
        return False

catalog/forms.py
import datetime

from django.contrib.auth.models import User
from django.core.exceptions import ValidationError
from django.forms import fields
from django.utils.translation import ugettext_lazy as _
from django import forms

from catalog.models import BookOrder


class RenewalBookForm(forms.Form):
    renewal_date = forms.DateField(help_text="Wprowadz datę od teraz do maksymalnie 4 tygodni w przód (domyślnie 3)")

    def clean_renewal_date(self):
        data = self.cleaned_data['renewal_date']

        if data < datetime.date.today():
            raise ValidationError(_('Niepoprawna data - data sprzed dnia dzisiejszego.'))

        if data > datetime.date.today() + datetime.timedelta(weeks=4):
            raise ValidationError(_('Niepoprawna data - wykracza poza dozwolone 4 tygodnie liczone od dziś.'))

        return data


class ChangeBookOrderStatusForm(forms.ModelForm):
    class Meta:
        model = BookOrder
        fields = ['status']

    def __init__(self, *args, **kwargs):
        super(ChangeBookOrderStatusForm, self).__init__(*args, **kwargs)
        status_choices = [('m', 'maintenance'), ('a', 'available')]
        self.fields['status'].choices = status_choices


class BookOrderForm(forms.ModelForm):

    class Meta:
        model = BookOrder
        fields = ['status', 'date_of_return', 'user']

    def __init__(self, *args, **kwargs):
        super(BookOrderForm, self).__init__(*args, **kwargs)
        user = kwargs['initial']['user']
        status_choices = [('o', 'on loan'), ('r', 'reserved')]

        self.fields['status'].choices = status_choices
        self.fields['user'].queryset = User.objects.filter(username=user)
        # self.fields['borrower'].empty_label = None # deleting  "-------" from choice list for borrower field

    def clean_due_back(self):
        due_back = self.cleaned_data["due_back"]
        # Check if a date is not in the past.
        if due_back < datetime.date.today():
            raise ValidationError(_('Niepoprawna data - data sprzed dnia dzisiejszego'))

        # Check if a date is in the allowed range (+4 weeks from today).
        if due_back > datetime.date.today() + datetime.timedelta(weeks=4):
            raise ValidationError(_('Niepoprawna data - wykracza poza dozwolone 4 tygodnie liczone od dziś.'))
        # Remember to always return the cleaned data.
        return due_back

catalog/views.py
import datetime

from django.contrib.auth.decorators import permission_required
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.http import HttpResponseRedirect
from django.shortcuts import render, get_object_or_404

# Create your views here.
from django.urls import reverse, reverse_lazy
from django.views import generic
from django.views.generic import CreateView, UpdateView, DeleteView

from catalog.forms import RenewalBookForm, ChangeBookOrderStatusForm, BookOrderForm
from catalog.models import Book, BookOrder, Author, Category


def index(request):
    num_books = Book.objects.all().count()
    num_instances = BookOrder.objects.all().count()
    num_categories = Category.objects.all().count()

    num_instances_available = BookOrder.objects.filter(status__exact='a').count()

    num_authors = Author.objects.count()

    context = {
        'num_books': num_books,
        'num_instances': num_instances,
        'num_instances_available': num_instances_available,
        'num_categories': num_categories,
        'num_authors': num_authors
    }

    return render(request, 'index.html', context=context)


class BookListView(generic.ListView):
    model = Book
    template_name = 'book_list.html'

    def get_queryset(self):
        """Function return last five Books"""
        return Book.objects.all()


class BookDetailView(generic.DetailView):
    model = Book
    template_name = 'book_detail.html'


class AuthorDetailView(generic.DetailView):
    model = Author
    template_name = 'author_detail.html'


class AuthorListView(generic.ListView):
    model = Author
    template_name = 'author_list.html'
    paginate_by = 10


class LoanedBooksByUserListView(LoginRequiredMixin, generic.ListView):
    model = BookOrder
    template_name = 'bookorder_list_borrowed_user.html'

    def get_queryset(self):
        return BookOrder.objects.filter(user=self.request.user).filter(status__exact='o').order_by('date_of_return')


class AllLoanedBooksByUsersListView(LoginRequiredMixin, PermissionRequiredMixin, generic.ListView):
    permission_required = 'catalog.can_mark_returned'
    model = BookOrder
    template_name = 'bookorder_list_borrowed.html'

    def get_queryset(self):
        return BookOrder.objects.all().filter(status__exact='o')


class AuthorCreate(LoginRequiredMixin, PermissionRequiredMixin, CreateView):
    permission_required = 'catalog.can_mark_returned'
    template_name = 'author_create.html'
    model = Author
    fields = '__all__'
    initial = {'date_of_death': '05/01/2018'}


class AuthorUpdate(LoginRequiredMixin, PermissionRequiredMixin, UpdateView):
    permission_required = 'catalog.can_mark_returned'
    template_name = 'author_update.html'
    model = Author
    fields = ['name', 'surname', 'date_of_death']


class AuthorDelete(LoginRequiredMixin, PermissionRequiredMixin, DeleteView):
    permission_required = 'catalog.can_mark_returned'
    template_name = 'author_confirm_delete.html'
    model = Author
    success_url = reverse_lazy('authors')


class BookCreate(LoginRequiredMixin, PermissionRequiredMixin, CreateView):
    permission_required = 'catalog.can_mark_returned'
    template_name = 'book_create.html'
    model = Book
    fields = '__all__'


class BookUpdate(LoginRequiredMixin, PermissionRequiredMixin, UpdateView):
    permission_required = 'catalog.can_mark_returned'
    template_name = 'book_update.html'
    model = Book
    fields = '__all__'


class BookDelete(LoginRequiredMixin, PermissionRequiredMixin, DeleteView):
    permission_required = 'catalog.can_mark_returned'
    template_name = 'book_confirm_delete.html'
    model = Book
    success_url = reverse_lazy('books')

class BookOrderDelete(LoginRequiredMixin, PermissionRequiredMixin, DeleteView):
    permission_required = 'catalog.can_mark_returned'
    template_name = 'bookorder_confirm_delete.html'
    model = BookOrder
    success_url = reverse_lazy('books')



class AllBooksEditListView(LoginRequiredMixin, PermissionRequiredMixin, generic.ListView):
    permission_required = 'catalog.can_mark_returned'
    model = Book
    template_name = 'book_list_edit.html'


@permission_required('catalog.can_mark_returned')
def renew_book_librarian(request, pk):
    book_order = get_object_or_404(BookOrder, pk=pk)

    if request.method == 'POST':

        form = RenewalBookForm(request.POST)

        if form.is_valid():
            book_order.date_of_return = form.cleaned_data['renewal_date']
            book_order.save()

            return HttpResponseRedirect(reverse('all-borrowed-books'))


    else:
        proposed_renewal_date = datetime.date.today() + datetime.timedelta(weeks=3)
        form = RenewalBookForm(initial={'renewal_date': proposed_renewal_date})

    context = {
        'form': form,
        'book_order': book_order,
    }

    return render(request, 'book_renew_librarian.html', context)


class AllAuthorsEditListView(LoginRequiredMixin, PermissionRequiredMixin, generic.ListView):
    permission_required = 'catalog.can_mark_returned'
    model = Author
    template_name = 'author_list_edit.html'


class BookOrderStatusUpdate(LoginRequiredMixin, PermissionRequiredMixin, UpdateView):
    permission_required = 'catalog.can_mark_returned'
    template_name = 'bookorder_form.html'
    model = BookOrder
    form_class = ChangeBookOrderStatusForm

    def get_success_url(self):
        book_pk = self.kwargs.get("book_pk")
        if book_pk:
            return reverse_lazy('book-detail', kwargs={'pk': book_pk})
        else:
            return reverse_lazy('borrowed-books-return')


class AllBooksToReturnListView(LoginRequiredMixin, PermissionRequiredMixin, generic.ListView):
    permission_required = 'catalog.can_mark_returned'
    model = BookOrder
    template_name = 'bookorder_list_borrowed_return.html'

    def get_queryset(self):
        return BookOrder.objects.all().filter(status__exact='o')

class BookInstanceBorrow(LoginRequiredMixin, UpdateView):
    template_name = 'bookinstance_form.html'
    model = BookOrder
    form_class = BookOrderForm

    def get_initial(self):
        return {
            "user": self.request.user,
            "date_of_return": datetime.date.today() + datetime.timedelta(weeks=3)
        }

    def get_success_url(self):
        return reverse_lazy('book-detail', kwargs={'pk': self.kwargs.get("book_pk")})

    def form_valid(self, form):
        response = form.save(commit=False)
        if form.is_valid():
            # process the data in form.cleaned_data as required (here we just write it to the model due_back field)
            response.due_back = form.cleaned_data['due_back']
            response.save()
        return super(BookInstanceBorrow, self).form_valid(form)

catalog/templates/author_confirm_delete.html
{% extends "base_generic.html" %}

{% block content %}

<h1>Usuwanie Autora</h1>

<p>Jesteś pewien/pewna że chcesz usunąć autora: {{ author }}?</p>

<form action="" method="POST">
  {% csrf_token %}
  <input type="submit" value="Tak, usuń.">
</form>

{% endblock %}

catalog/templates/author_list.html
{% extends "base_generic.html" %}

{% block content %}
  <h1>Authors List</h1>
  <ul>
    {% for author in author_list %}
      <li>
        <a href="{{ author.get_absolute_url }}">{{ author.name }} {{ author.surname }}</a>
      </li>
    {% endfor %}
  </ul>
{% endblock %}

catalog/templates/author_list_edit.html
{% extends "base_generic.html" %}

{% block content %}
  <h1>Authors List</h1>
  <ul>
    {% for author in author_list %}
      <li>
        {{ author.name }} {{ author.surname }}  <a href="{% url 'author-update' author.pk %}">(Update)</a> <a href="{% url 'author-delete' author.pk %}">(Delete)</a>
      </li>
    {% endfor %}
  </ul>

{% endblock %}

catalog/templates/author_update.html
{% extends "base_generic.html" %}

{% block content %}
  <h1>Author</h1>
  <form action="" method="post">
    {% csrf_token %}
    <table>
    {{ form.as_table }}
    </table>
    <input type="submit" value="Zatwierdź">
  </form>
{% endblock %}

catalog/templates/base_generic.html
<!DOCTYPE html>
<html lang="pl">
<head>
    {% block title %}<title>Local Library</title>{% endblock %}
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
          integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css?family=Poppins:300,400,500,600,700,800,900" rel="stylesheet">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>
<body>

<div class="wrapper d-flex align-items-stretch">
    <!-- Side bar  -->
    {% block sidebar %}
        <nav id="sidebar">
            <div class="custom-menu">
                <button type="button" id="sidebarCollapse" class="btn btn-primary">
                </button>
            </div>
            <div class="img bg-wrap text-center py-4" style="background-image: url({% static 'images/bg_1.jpg' %});">
                <h3 class="font-italic text-white"><a href="{% url 'index' %}" class="text-white">Local Library</a></h3>
            </div>
            <ul class="list-unstyled components mb-5">
                {% if user.is_authenticated %}
                    <li><a href="{% url 'logout' %}?next={{ request.path }}">Logout</a></li>
                    <li>
                        <center>Hello {{ user.get_username }} </center>
                    </li>
                    <li><a href="{% url 'my-borrowed' %}"><span class="fa fa-book mr-3"></span>My Borrowed Books</a>
                    </li>
                {% else %}
                    <li><a href="{% url 'login' %}?next={{ request.path }}">Login</a></li>
                    <li>
                        <a href="{% url 'django_registration_register' %}"><span class="fa fa-sign-in mr-3"></span>Register</a>
                    </li>
                {% endif %}
                <li>
                    <a href="{% url 'index' %}"><span class="fa fa-home mr-3"></span> Main Page</a>
                </li>
                <li>
                    <a href="{% url 'books' %}"><span class="fa fa-book mr-3 "></span>Books</a>
                </li>
                <li>
                    <a href="{% url 'authors' %}"><span class="fa fa-user mr-3"></span>Authors</a>
                </li>

                {% if perms.catalog.can_mark_returned %}
                    <hr>
                    <li><strong>
                        <center>Only for Employee</center>
                    </strong></li>
                    <hr>
                    <li>
                        <center>Books</center>
                    </li>
                    <li><a href="{% url 'all-borrowed-books' %}"><span class="fa fa-book mr-3"></span>Przedłuż
                        wypożyczone książki</a></li>
                    <li><a href="{% url 'book-create' %}"><span class="fa fa-book mr-3"></span>Create Book</a></li>
                    <li><a href="{% url 'books-edit' %}"><span class="fa fa-book mr-3"></span>Edit Books</a></li>
                    <li><a href="{% url 'borrowed-books-return' %}"><span class="fa fa-book mr-3"></span>Return
                        Books</a></li>
                    <hr>
                    <li>
                        <center>Authors</center>
                    </li>
                    <li><a href="{% url 'author-create' %}"><span class="fa fa-book mr-3"></span>Create Author</a></li>
                    <li><a href="{% url 'authors-edit' %}"><span class="fa fa-book mr-3"></span>Edit Authors</a></li>
                {% endif %}
                <hr>
            </ul>
        </nav>
    {% endblock %}

    <!-- Page Content  -->
    <div id="content" class="p-4 p-md-5 pt-5">
        {% block content %}{% endblock %}
    </div>
</div>

<script src="{% static 'js/jquery.min.js' %}"></script>
<script src="{% static 'js/popper.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
<script src="{% static 'js/main.js' %}"></script>

</body>
</html>

catalog/templates/book_confirm_delete.html
{% extends "base_generic.html" %}

{% block content %}

<h1>Delete Book</h1>

<p>Jesteś pewien/pewna że chcesz usunąć autora: {{ book }}?</p>

<form action="" method="POST">
  {% csrf_token %}
  <input type="submit" value="Tak, usuń.">
</form>

{% endblock %}

catalog/templates/book_create.html
{% extends "base_generic.html" %}

{% block content %}
  <h1>Book</h1>
  <form action="" method="post">
    {% csrf_token %}
    <table>
    {{ form.as_table }}
    </table>
    <input type="submit" value="Zatwierdź">
  </form>
{% endblock %}

catalog/templates/book_detail.html
{% extends "base_generic.html" %}

{% block content %}
    <h1>Title: {{ book.title }}</h1>

    <p><strong>Auhor:</strong> <a href="{{ book.author.get_absolute_url }}">{{ book.author }}</a></p>
    <p><strong>Descritpion:</strong> {{ book.description }}</p>
    <p><strong>ISBN:</strong> {{ book.isbn }}</p>
    <p><strong>Language:</strong> {{ book.language }}</p>
    <p><strong>Catgegory:</strong> {{ book.category.all|join:", " }}</p>

    {% if perms.catalog.can_mark_returned %}
        <a href="{% url 'book-update' book.pk %}">Update</a> <a href="{% url 'book-delete' book.pk %}">Delete</a>
    {% endif %}

    <div style="margin-left:20px;margin-top:20px">
        <h4>Copies</h4>

        {% for copy in book.bookorder_set.all %}
            <hr>
            <p class="{% if copy.status == 'a' %}text-success{% elif copy.status == 'm' %}text-danger{% else %}text-warning{% endif %}">
                {{ copy.get_status_display }}
            </p>
            {% if perms.catalog.can_mark_returned %}
                {% if copy.status == 'o' or copy.status == 'r' %}
                    <p><strong>Borrow to:</strong> {{ copy.due_back }}</p>
                {% endif %}
            {% endif %}
            <p><strong>Imprint:</strong> {{ copy.imprint }}</p>
            <p class="text-muted"><strong>Id:</strong> {{ copy.id }}</p>
{#            {% if copy.status == 'a' %}#}
{#                <p>#}
{#                    <a href="{% url 'bookinstance_borrow' pk=copy.id book_pk=book.pk book_title=book.title %}">Zarezerwuj</a>#}
{#                    <a href="{% url 'bookinstance_borrow' pk=copy.id book_pk=book.pk book_title=book.title %}">Wypożycz</a>#}
{#                </p>#}
{#            {% endif %}#}
            <a href="{% url 'book-return' copy.id %}">Return book</a>
            <a href="{% url 'book-order-delete' copy.id %}">Delete Book</a>
        {% endfor %}
    </div>
{% endblock %}

catalog/templates/book_list.html
{% extends "base_generic.html" %}

{% block content %}
  <h1>Books List</h1>
  {% if book_list %}
  <ul>
    {% for book in book_list %}
      <li>
        <a href="{{ book.get_absolute_url }}">{{ book.title }}</a> ({{book.author}})
      </li>
    {% endfor %}
  </ul>
  {% else %}
    <p>Library is empty.</p>
  {% endif %}       
{% endblock %}

catalog/templates/book_list_edit.html
{% extends "base_generic.html" %}

{% block content %}
  <h1>Book List</h1>
  <ul>
    {% for book in book_list %}
      <li>
        {{ book.title }}  <a href="{% url 'book-update' book.pk %}">(Update)</a> <a href="{% url 'book-delete' book.pk %}">(Delete)</a>
      </li>
    {% endfor %}
  </ul>

{% endblock %}

catalog/templates/book_renew_librarian.html
{% extends "base_generic.html" %}

{% block content %}
  <h1>Przedłuż wypożyczenie: {{ book_order.book.title }}</h1>
  <p>Wypożyczony przez: {{ book_order.user }}</p>
  <p{% if book_order.is_overdue %} class="text-danger"{% endif %}>Wypożyczony do: {{ book_order.date_of_return }}</p>

  <form action="" method="post">
    {% csrf_token %}
    <table>
    {{ form.as_table }}
    </table>
    <input type="submit" value="Zatwierdź">
  </form>
{% endblock %}

catalog/templates/bookorder_confirm_delete.html
{% extends "base_generic.html" %}

{% block content %}

<h1>Usuwanie BookOrder</h1>

<p>Jesteś pewien/pewna że chcesz usunąć autora: {{ bookorder }}?</p>

<form action="" method="POST">
  {% csrf_token %}
  <input type="submit" value="Tak, usuń.">
</form>

{% endblock %}

catalog/templates/bookorder_list_borrowed_user.html
{% extends "base_generic.html" %}

{% block content %}
    <h1>My borrowed books</h1>

    {% if bookorder_list %}
    <ul>
      {% for bookorder in bookorder_list %}
      <li class="{% if bookorder.is_overdue %}text-danger{% endif %}">
        <a href="{% url 'book-detail' bookorder.book.pk %}">{{bookorder.book.title}}</a> ({{ bookorder.date_of_return }})
      </li>
      {% endfor %}
    </ul>

    {% else %}
      <p>Empty.</p>
    {% endif %}
{% endblock %}

catalog/templates/index.html
{% extends "base_generic.html" %}

{% block title %}
    <title></title>
{% endblock %}

{% block content %}
    <h1>Local Library - Home</h1>
    <p>Welcome to the Local Library</p>
    <p>The library has the following items:</p>
    <ul>
        <li><strong>Books:</strong> {{ num_books }}</li>
        <li><strong>Categories:</strong> {{ num_categories }}</li>
        <li><strong>Number of copies:</strong> {{ num_instances }}</li>
        <li><strong>Number of copies available:</strong> {{ num_instances_available }}</li>
        <li><strong>Authors:</strong> {{ num_authors }}</li>
    </ul>
{% endblock %}